//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Cliente.ProxyUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioBE", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    [System.SerializableAttribute()]
    public partial class UsuarioBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Contra_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Correo_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecRegistro_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Naci_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Nivel_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tele_UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Usuario {
            get {
                return this.Ape_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_UsuarioField, value) != true)) {
                    this.Ape_UsuarioField = value;
                    this.RaisePropertyChanged("Ape_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contra_Usuario {
            get {
                return this.Contra_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Contra_UsuarioField, value) != true)) {
                    this.Contra_UsuarioField = value;
                    this.RaisePropertyChanged("Contra_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_Usuario {
            get {
                return this.Correo_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Correo_UsuarioField, value) != true)) {
                    this.Correo_UsuarioField = value;
                    this.RaisePropertyChanged("Correo_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_Usuario {
            get {
                return this.Dni_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_UsuarioField, value) != true)) {
                    this.Dni_UsuarioField = value;
                    this.RaisePropertyChanged("Dni_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecRegistro_Usuario {
            get {
                return this.FecRegistro_UsuarioField;
            }
            set {
                if ((this.FecRegistro_UsuarioField.Equals(value) != true)) {
                    this.FecRegistro_UsuarioField = value;
                    this.RaisePropertyChanged("FecRegistro_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Usuario {
            get {
                return this.Id_UsuarioField;
            }
            set {
                if ((this.Id_UsuarioField.Equals(value) != true)) {
                    this.Id_UsuarioField = value;
                    this.RaisePropertyChanged("Id_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Naci_Usuario {
            get {
                return this.Naci_UsuarioField;
            }
            set {
                if ((this.Naci_UsuarioField.Equals(value) != true)) {
                    this.Naci_UsuarioField = value;
                    this.RaisePropertyChanged("Naci_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Nivel_Usuario {
            get {
                return this.Nivel_UsuarioField;
            }
            set {
                if ((this.Nivel_UsuarioField.Equals(value) != true)) {
                    this.Nivel_UsuarioField = value;
                    this.RaisePropertyChanged("Nivel_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Usuario {
            get {
                return this.Nom_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_UsuarioField, value) != true)) {
                    this.Nom_UsuarioField = value;
                    this.RaisePropertyChanged("Nom_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tele_Usuario {
            get {
                return this.Tele_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Tele_UsuarioField, value) != true)) {
                    this.Tele_UsuarioField = value;
                    this.RaisePropertyChanged("Tele_Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUsuarios.IServicioUsuarios")]
    public interface IServicioUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/GetUsuario", ReplyAction="http://tempuri.org/IServicioUsuarios/GetUsuarioResponse")]
        Windows_Cliente.ProxyUsuarios.UsuarioBE GetUsuario(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/GetUsuario", ReplyAction="http://tempuri.org/IServicioUsuarios/GetUsuarioResponse")]
        System.Threading.Tasks.Task<Windows_Cliente.ProxyUsuarios.UsuarioBE> GetUsuarioAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuariosChannel : Windows_Cliente.ProxyUsuarios.IServicioUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuariosClient : System.ServiceModel.ClientBase<Windows_Cliente.ProxyUsuarios.IServicioUsuarios>, Windows_Cliente.ProxyUsuarios.IServicioUsuarios {
        
        public ServicioUsuariosClient() {
        }
        
        public ServicioUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Windows_Cliente.ProxyUsuarios.UsuarioBE GetUsuario(string correo) {
            return base.Channel.GetUsuario(correo);
        }
        
        public System.Threading.Tasks.Task<Windows_Cliente.ProxyUsuarios.UsuarioBE> GetUsuarioAsync(string correo) {
            return base.Channel.GetUsuarioAsync(correo);
        }
    }
}
