//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.Reclamo = new HashSet<Reclamo>();
        }
    
        public int idReserva { get; set; }
        public int idUsuario { get; set; }
        public int idRestaurante { get; set; }
        public System.DateTime fechaReserva { get; set; }
        public int cantPersonas { get; set; }
        public int estadoReserva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamo> Reclamo { get; set; }
        public virtual Restaurantes Restaurantes { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
