//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseña
    {
        public int idReseña { get; set; }
        public int idUsuario { get; set; }
        public int idRestaurante { get; set; }
        public string tituloReseña { get; set; }
        public string contenidoReseña { get; set; }
        public Nullable<System.DateTime> fecRegistroReseña { get; set; }
    
        public virtual Restaurantes Restaurantes { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
