//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurantes()
        {
            this.Reseña = new HashSet<Reseña>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int idRestaurante { get; set; }
        public int idCategoria { get; set; }
        public int idDistrito { get; set; }
        public string nomRestaurante { get; set; }
        public string direcRestaurante { get; set; }
        public string teleRestaurante { get; set; }
        public Nullable<System.DateTime> fecRegistroRestaurante { get; set; }
        public string usuRegistroRestaurante { get; set; }
        public Nullable<System.DateTime> fecUltModiRestaurante { get; set; }
        public string usuUltModiRestaurante { get; set; }
        public int estadoRestaurante { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Distrito Distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reseña> Reseña { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
