//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListadoReservas
    {
        public int idReserva { get; set; }
        public System.DateTime fechaReserva { get; set; }
        public int cantPersonas { get; set; }
        public int idRestaurante { get; set; }
        public string nomRestaurante { get; set; }
        public int idUsuario { get; set; }
        public string direcRestaurante { get; set; }
        public int idDistrito { get; set; }
        public string nomDistrito { get; set; }
        public string Estado { get; set; }
    }
}
