//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Cliente.ProxyRestaurante {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyRestaurante.IServicioRestaurantes")]
    public interface IServicioRestaurantes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantes", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesResponse")]
        ServiciosWCF.RestauranteBE[] GetAllRestaurantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantes", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivo", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivoResponse")]
        ServiciosWCF.RestauranteBE[] GetAllRestaurantesActivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivo", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivoResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesActivoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetRestauranteResponse")]
        ServiciosWCF.RestauranteBE GetRestaurante(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetRestauranteResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE> GetRestauranteAsync(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/InsertRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/InsertRestauranteResponse")]
        bool InsertRestaurante(ServiciosWCF.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/InsertRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/InsertRestauranteResponse")]
        System.Threading.Tasks.Task<bool> InsertRestauranteAsync(ServiciosWCF.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/UpdateRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/UpdateRestauranteResponse")]
        bool UpdateRestaurante(ServiciosWCF.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/UpdateRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/UpdateRestauranteResponse")]
        System.Threading.Tasks.Task<bool> UpdateRestauranteAsync(ServiciosWCF.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorDistrito", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorDistritoResponse")]
        ServiciosWCF.RestauranteBE[] GetAllRestaurantesPorDistrito(short idDistri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorDistrito", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorDistritoResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesPorDistritoAsync(short idDistri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoria", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaResponse")]
        ServiciosWCF.RestauranteBE[] GetAllRestaurantesPorCategoria(short idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoria", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesPorCategoriaAsync(short idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaDistrito", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaDistritoRe" +
            "sponse")]
        ServiciosWCF.RestauranteBE[] GetAllRestaurantesPorCategoriaDistrito(short idCate, short idDistri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaDistrito", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaDistritoRe" +
            "sponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesPorCategoriaDistritoAsync(short idCate, short idDistri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllDistritos", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllDistritosResponse")]
        ServiciosWCF.RestauranteBE[] GetAllDistritos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllDistritos", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllDistritosResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllDistritosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllCategorias", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllCategoriasResponse")]
        ServiciosWCF.RestauranteBE[] GetAllCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllCategorias", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllCategoriasResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllCategoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRestaurantesChannel : Web_Cliente.ProxyRestaurante.IServicioRestaurantes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRestaurantesClient : System.ServiceModel.ClientBase<Web_Cliente.ProxyRestaurante.IServicioRestaurantes>, Web_Cliente.ProxyRestaurante.IServicioRestaurantes {
        
        public ServicioRestaurantesClient() {
        }
        
        public ServicioRestaurantesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRestaurantesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRestaurantesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRestaurantesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiciosWCF.RestauranteBE[] GetAllRestaurantes() {
            return base.Channel.GetAllRestaurantes();
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesAsync() {
            return base.Channel.GetAllRestaurantesAsync();
        }
        
        public ServiciosWCF.RestauranteBE[] GetAllRestaurantesActivo() {
            return base.Channel.GetAllRestaurantesActivo();
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesActivoAsync() {
            return base.Channel.GetAllRestaurantesActivoAsync();
        }
        
        public ServiciosWCF.RestauranteBE GetRestaurante(short idResta) {
            return base.Channel.GetRestaurante(idResta);
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE> GetRestauranteAsync(short idResta) {
            return base.Channel.GetRestauranteAsync(idResta);
        }
        
        public bool InsertRestaurante(ServiciosWCF.RestauranteBE objRestauranteBE) {
            return base.Channel.InsertRestaurante(objRestauranteBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertRestauranteAsync(ServiciosWCF.RestauranteBE objRestauranteBE) {
            return base.Channel.InsertRestauranteAsync(objRestauranteBE);
        }
        
        public bool UpdateRestaurante(ServiciosWCF.RestauranteBE objRestauranteBE) {
            return base.Channel.UpdateRestaurante(objRestauranteBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRestauranteAsync(ServiciosWCF.RestauranteBE objRestauranteBE) {
            return base.Channel.UpdateRestauranteAsync(objRestauranteBE);
        }
        
        public ServiciosWCF.RestauranteBE[] GetAllRestaurantesPorDistrito(short idDistri) {
            return base.Channel.GetAllRestaurantesPorDistrito(idDistri);
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesPorDistritoAsync(short idDistri) {
            return base.Channel.GetAllRestaurantesPorDistritoAsync(idDistri);
        }
        
        public ServiciosWCF.RestauranteBE[] GetAllRestaurantesPorCategoria(short idCate) {
            return base.Channel.GetAllRestaurantesPorCategoria(idCate);
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesPorCategoriaAsync(short idCate) {
            return base.Channel.GetAllRestaurantesPorCategoriaAsync(idCate);
        }
        
        public ServiciosWCF.RestauranteBE[] GetAllRestaurantesPorCategoriaDistrito(short idCate, short idDistri) {
            return base.Channel.GetAllRestaurantesPorCategoriaDistrito(idCate, idDistri);
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesPorCategoriaDistritoAsync(short idCate, short idDistri) {
            return base.Channel.GetAllRestaurantesPorCategoriaDistritoAsync(idCate, idDistri);
        }
        
        public ServiciosWCF.RestauranteBE[] GetAllDistritos() {
            return base.Channel.GetAllDistritos();
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllDistritosAsync() {
            return base.Channel.GetAllDistritosAsync();
        }
        
        public ServiciosWCF.RestauranteBE[] GetAllCategorias() {
            return base.Channel.GetAllCategorias();
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllCategoriasAsync() {
            return base.Channel.GetAllCategoriasAsync();
        }
    }
}
