//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Cliente.ProxyResena {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyResena.IServicioResenas")]
    public interface IServicioResenas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñas", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasResponse")]
        ServiciosWCF.ReseñaBE[] GetAllReseñas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñas", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.ReseñaBE[]> GetAllReseñasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñasRestaurante", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasRestauranteResponse")]
        ServiciosWCF.ReseñaBE[] GetAllReseñasRestaurante(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñasRestaurante", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasRestauranteResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.ReseñaBE[]> GetAllReseñasRestauranteAsync(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñasUsuario", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasUsuarioResponse")]
        ServiciosWCF.ReseñaBE[] GetAllReseñasUsuario(short idUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñasUsuario", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasUsuarioResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.ReseñaBE[]> GetAllReseñasUsuarioAsync(short idUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetReseña", ReplyAction="http://tempuri.org/IServicioResenas/GetReseñaResponse")]
        ServiciosWCF.ReseñaBE GetReseña(short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetReseña", ReplyAction="http://tempuri.org/IServicioResenas/GetReseñaResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.ReseñaBE> GetReseñaAsync(short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/UpdateReseña", ReplyAction="http://tempuri.org/IServicioResenas/UpdateReseñaResponse")]
        bool UpdateReseña(ServiciosWCF.ReseñaBE objReseñaBE, short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/UpdateReseña", ReplyAction="http://tempuri.org/IServicioResenas/UpdateReseñaResponse")]
        System.Threading.Tasks.Task<bool> UpdateReseñaAsync(ServiciosWCF.ReseñaBE objReseñaBE, short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/InsertReseña", ReplyAction="http://tempuri.org/IServicioResenas/InsertReseñaResponse")]
        bool InsertReseña(ServiciosWCF.ReseñaBE objReseñaBE, short idUsua, short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/InsertReseña", ReplyAction="http://tempuri.org/IServicioResenas/InsertReseñaResponse")]
        System.Threading.Tasks.Task<bool> InsertReseñaAsync(ServiciosWCF.ReseñaBE objReseñaBE, short idUsua, short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/DeleteReseña", ReplyAction="http://tempuri.org/IServicioResenas/DeleteReseñaResponse")]
        bool DeleteReseña(short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/DeleteReseña", ReplyAction="http://tempuri.org/IServicioResenas/DeleteReseñaResponse")]
        System.Threading.Tasks.Task<bool> DeleteReseñaAsync(short idRese);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioResenasChannel : Web_Cliente.ProxyResena.IServicioResenas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioResenasClient : System.ServiceModel.ClientBase<Web_Cliente.ProxyResena.IServicioResenas>, Web_Cliente.ProxyResena.IServicioResenas {
        
        public ServicioResenasClient() {
        }
        
        public ServicioResenasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioResenasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResenasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResenasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiciosWCF.ReseñaBE[] GetAllReseñas() {
            return base.Channel.GetAllReseñas();
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.ReseñaBE[]> GetAllReseñasAsync() {
            return base.Channel.GetAllReseñasAsync();
        }
        
        public ServiciosWCF.ReseñaBE[] GetAllReseñasRestaurante(short idResta) {
            return base.Channel.GetAllReseñasRestaurante(idResta);
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.ReseñaBE[]> GetAllReseñasRestauranteAsync(short idResta) {
            return base.Channel.GetAllReseñasRestauranteAsync(idResta);
        }
        
        public ServiciosWCF.ReseñaBE[] GetAllReseñasUsuario(short idUsua) {
            return base.Channel.GetAllReseñasUsuario(idUsua);
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.ReseñaBE[]> GetAllReseñasUsuarioAsync(short idUsua) {
            return base.Channel.GetAllReseñasUsuarioAsync(idUsua);
        }
        
        public ServiciosWCF.ReseñaBE GetReseña(short idRese) {
            return base.Channel.GetReseña(idRese);
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.ReseñaBE> GetReseñaAsync(short idRese) {
            return base.Channel.GetReseñaAsync(idRese);
        }
        
        public bool UpdateReseña(ServiciosWCF.ReseñaBE objReseñaBE, short idRese) {
            return base.Channel.UpdateReseña(objReseñaBE, idRese);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateReseñaAsync(ServiciosWCF.ReseñaBE objReseñaBE, short idRese) {
            return base.Channel.UpdateReseñaAsync(objReseñaBE, idRese);
        }
        
        public bool InsertReseña(ServiciosWCF.ReseñaBE objReseñaBE, short idUsua, short idResta) {
            return base.Channel.InsertReseña(objReseñaBE, idUsua, idResta);
        }
        
        public System.Threading.Tasks.Task<bool> InsertReseñaAsync(ServiciosWCF.ReseñaBE objReseñaBE, short idUsua, short idResta) {
            return base.Channel.InsertReseñaAsync(objReseñaBE, idUsua, idResta);
        }
        
        public bool DeleteReseña(short idRese) {
            return base.Channel.DeleteReseña(idRese);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteReseñaAsync(short idRese) {
            return base.Channel.DeleteReseñaAsync(idRese);
        }
    }
}
