//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Cliente.ProxyRestaurante {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestauranteBE", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    [System.SerializableAttribute()]
    public partial class RestauranteBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Cate_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Direc_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Distri_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Estado_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecRegistro_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecUltModi_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_CategoriaRestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_DistritoRestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_EstadoRestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tele_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuRegistro_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuUltModi_RestauranteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Cate_Restaurante {
            get {
                return this.Cate_RestauranteField;
            }
            set {
                if ((this.Cate_RestauranteField.Equals(value) != true)) {
                    this.Cate_RestauranteField = value;
                    this.RaisePropertyChanged("Cate_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direc_Restaurante {
            get {
                return this.Direc_RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Direc_RestauranteField, value) != true)) {
                    this.Direc_RestauranteField = value;
                    this.RaisePropertyChanged("Direc_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Distri_Restaurante {
            get {
                return this.Distri_RestauranteField;
            }
            set {
                if ((this.Distri_RestauranteField.Equals(value) != true)) {
                    this.Distri_RestauranteField = value;
                    this.RaisePropertyChanged("Distri_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estado_Restaurante {
            get {
                return this.Estado_RestauranteField;
            }
            set {
                if ((this.Estado_RestauranteField.Equals(value) != true)) {
                    this.Estado_RestauranteField = value;
                    this.RaisePropertyChanged("Estado_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecRegistro_Restaurante {
            get {
                return this.FecRegistro_RestauranteField;
            }
            set {
                if ((this.FecRegistro_RestauranteField.Equals(value) != true)) {
                    this.FecRegistro_RestauranteField = value;
                    this.RaisePropertyChanged("FecRegistro_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecUltModi_Restaurante {
            get {
                return this.FecUltModi_RestauranteField;
            }
            set {
                if ((this.FecUltModi_RestauranteField.Equals(value) != true)) {
                    this.FecUltModi_RestauranteField = value;
                    this.RaisePropertyChanged("FecUltModi_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Restaurante {
            get {
                return this.Id_RestauranteField;
            }
            set {
                if ((this.Id_RestauranteField.Equals(value) != true)) {
                    this.Id_RestauranteField = value;
                    this.RaisePropertyChanged("Id_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_CategoriaRestaurante {
            get {
                return this.Nom_CategoriaRestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_CategoriaRestauranteField, value) != true)) {
                    this.Nom_CategoriaRestauranteField = value;
                    this.RaisePropertyChanged("Nom_CategoriaRestaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_DistritoRestaurante {
            get {
                return this.Nom_DistritoRestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_DistritoRestauranteField, value) != true)) {
                    this.Nom_DistritoRestauranteField = value;
                    this.RaisePropertyChanged("Nom_DistritoRestaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_EstadoRestaurante {
            get {
                return this.Nom_EstadoRestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_EstadoRestauranteField, value) != true)) {
                    this.Nom_EstadoRestauranteField = value;
                    this.RaisePropertyChanged("Nom_EstadoRestaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Restaurante {
            get {
                return this.Nom_RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_RestauranteField, value) != true)) {
                    this.Nom_RestauranteField = value;
                    this.RaisePropertyChanged("Nom_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tele_Restaurante {
            get {
                return this.Tele_RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Tele_RestauranteField, value) != true)) {
                    this.Tele_RestauranteField = value;
                    this.RaisePropertyChanged("Tele_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuRegistro_Restaurante {
            get {
                return this.UsuRegistro_RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuRegistro_RestauranteField, value) != true)) {
                    this.UsuRegistro_RestauranteField = value;
                    this.RaisePropertyChanged("UsuRegistro_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuUltModi_Restaurante {
            get {
                return this.UsuUltModi_RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuUltModi_RestauranteField, value) != true)) {
                    this.UsuUltModi_RestauranteField = value;
                    this.RaisePropertyChanged("UsuUltModi_Restaurante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyRestaurante.IServicioRestaurantes")]
    public interface IServicioRestaurantes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantes", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesResponse")]
        MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantes", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivo", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivoResponse")]
        MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantesActivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivo", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivoResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesActivoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetRestauranteResponse")]
        MVC_Cliente.ProxyRestaurante.RestauranteBE GetRestaurante(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetRestauranteResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE> GetRestauranteAsync(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/InsertRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/InsertRestauranteResponse")]
        bool InsertRestaurante(MVC_Cliente.ProxyRestaurante.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/InsertRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/InsertRestauranteResponse")]
        System.Threading.Tasks.Task<bool> InsertRestauranteAsync(MVC_Cliente.ProxyRestaurante.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/UpdateRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/UpdateRestauranteResponse")]
        bool UpdateRestaurante(MVC_Cliente.ProxyRestaurante.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/UpdateRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/UpdateRestauranteResponse")]
        System.Threading.Tasks.Task<bool> UpdateRestauranteAsync(MVC_Cliente.ProxyRestaurante.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorDistrito", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorDistritoResponse")]
        MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantesPorDistrito(short idDistri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorDistrito", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorDistritoResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesPorDistritoAsync(short idDistri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoria", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaResponse")]
        MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantesPorCategoria(short idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoria", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesPorCategoriaAsync(short idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaDistrito", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaDistritoRe" +
            "sponse")]
        MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantesPorCategoriaDistrito(short idCate, short idDistri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaDistrito", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesPorCategoriaDistritoRe" +
            "sponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesPorCategoriaDistritoAsync(short idCate, short idDistri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllDistritos", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllDistritosResponse")]
        MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllDistritos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllDistritos", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllDistritosResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllDistritosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllCategorias", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllCategoriasResponse")]
        MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllCategorias", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllCategoriasResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllCategoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRestaurantesChannel : MVC_Cliente.ProxyRestaurante.IServicioRestaurantes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRestaurantesClient : System.ServiceModel.ClientBase<MVC_Cliente.ProxyRestaurante.IServicioRestaurantes>, MVC_Cliente.ProxyRestaurante.IServicioRestaurantes {
        
        public ServicioRestaurantesClient() {
        }
        
        public ServicioRestaurantesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRestaurantesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRestaurantesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRestaurantesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantes() {
            return base.Channel.GetAllRestaurantes();
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesAsync() {
            return base.Channel.GetAllRestaurantesAsync();
        }
        
        public MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantesActivo() {
            return base.Channel.GetAllRestaurantesActivo();
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesActivoAsync() {
            return base.Channel.GetAllRestaurantesActivoAsync();
        }
        
        public MVC_Cliente.ProxyRestaurante.RestauranteBE GetRestaurante(short idResta) {
            return base.Channel.GetRestaurante(idResta);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE> GetRestauranteAsync(short idResta) {
            return base.Channel.GetRestauranteAsync(idResta);
        }
        
        public bool InsertRestaurante(MVC_Cliente.ProxyRestaurante.RestauranteBE objRestauranteBE) {
            return base.Channel.InsertRestaurante(objRestauranteBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertRestauranteAsync(MVC_Cliente.ProxyRestaurante.RestauranteBE objRestauranteBE) {
            return base.Channel.InsertRestauranteAsync(objRestauranteBE);
        }
        
        public bool UpdateRestaurante(MVC_Cliente.ProxyRestaurante.RestauranteBE objRestauranteBE) {
            return base.Channel.UpdateRestaurante(objRestauranteBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRestauranteAsync(MVC_Cliente.ProxyRestaurante.RestauranteBE objRestauranteBE) {
            return base.Channel.UpdateRestauranteAsync(objRestauranteBE);
        }
        
        public MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantesPorDistrito(short idDistri) {
            return base.Channel.GetAllRestaurantesPorDistrito(idDistri);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesPorDistritoAsync(short idDistri) {
            return base.Channel.GetAllRestaurantesPorDistritoAsync(idDistri);
        }
        
        public MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantesPorCategoria(short idCate) {
            return base.Channel.GetAllRestaurantesPorCategoria(idCate);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesPorCategoriaAsync(short idCate) {
            return base.Channel.GetAllRestaurantesPorCategoriaAsync(idCate);
        }
        
        public MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllRestaurantesPorCategoriaDistrito(short idCate, short idDistri) {
            return base.Channel.GetAllRestaurantesPorCategoriaDistrito(idCate, idDistri);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllRestaurantesPorCategoriaDistritoAsync(short idCate, short idDistri) {
            return base.Channel.GetAllRestaurantesPorCategoriaDistritoAsync(idCate, idDistri);
        }
        
        public MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllDistritos() {
            return base.Channel.GetAllDistritos();
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllDistritosAsync() {
            return base.Channel.GetAllDistritosAsync();
        }
        
        public MVC_Cliente.ProxyRestaurante.RestauranteBE[] GetAllCategorias() {
            return base.Channel.GetAllCategorias();
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyRestaurante.RestauranteBE[]> GetAllCategoriasAsync() {
            return base.Channel.GetAllCategoriasAsync();
        }
    }
}
