//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Cliente.ProxyReserva {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaBE", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    [System.SerializableAttribute()]
    public partial class ReservaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Cant_PersonasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Cant_VecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Direc_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Estado_ReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_ReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_ReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_DistritoRestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usua_ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usua_CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usua_DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usua_NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Cant_Personas {
            get {
                return this.Cant_PersonasField;
            }
            set {
                if ((this.Cant_PersonasField.Equals(value) != true)) {
                    this.Cant_PersonasField = value;
                    this.RaisePropertyChanged("Cant_Personas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Cant_Veces {
            get {
                return this.Cant_VecesField;
            }
            set {
                if ((this.Cant_VecesField.Equals(value) != true)) {
                    this.Cant_VecesField = value;
                    this.RaisePropertyChanged("Cant_Veces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direc_Restaurante {
            get {
                return this.Direc_RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Direc_RestauranteField, value) != true)) {
                    this.Direc_RestauranteField = value;
                    this.RaisePropertyChanged("Direc_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado_Reserva {
            get {
                return this.Estado_ReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.Estado_ReservaField, value) != true)) {
                    this.Estado_ReservaField = value;
                    this.RaisePropertyChanged("Estado_Reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Reserva {
            get {
                return this.Fecha_ReservaField;
            }
            set {
                if ((this.Fecha_ReservaField.Equals(value) != true)) {
                    this.Fecha_ReservaField = value;
                    this.RaisePropertyChanged("Fecha_Reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Reserva {
            get {
                return this.Id_ReservaField;
            }
            set {
                if ((this.Id_ReservaField.Equals(value) != true)) {
                    this.Id_ReservaField = value;
                    this.RaisePropertyChanged("Id_Reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Restaurante {
            get {
                return this.Id_RestauranteField;
            }
            set {
                if ((this.Id_RestauranteField.Equals(value) != true)) {
                    this.Id_RestauranteField = value;
                    this.RaisePropertyChanged("Id_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Usuario {
            get {
                return this.Id_UsuarioField;
            }
            set {
                if ((this.Id_UsuarioField.Equals(value) != true)) {
                    this.Id_UsuarioField = value;
                    this.RaisePropertyChanged("Id_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_DistritoRestaurante {
            get {
                return this.Nom_DistritoRestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_DistritoRestauranteField, value) != true)) {
                    this.Nom_DistritoRestauranteField = value;
                    this.RaisePropertyChanged("Nom_DistritoRestaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Restaurante {
            get {
                return this.Nom_RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_RestauranteField, value) != true)) {
                    this.Nom_RestauranteField = value;
                    this.RaisePropertyChanged("Nom_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usua_Apellido {
            get {
                return this.Usua_ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.Usua_ApellidoField, value) != true)) {
                    this.Usua_ApellidoField = value;
                    this.RaisePropertyChanged("Usua_Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usua_Correo {
            get {
                return this.Usua_CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.Usua_CorreoField, value) != true)) {
                    this.Usua_CorreoField = value;
                    this.RaisePropertyChanged("Usua_Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usua_Dni {
            get {
                return this.Usua_DniField;
            }
            set {
                if ((object.ReferenceEquals(this.Usua_DniField, value) != true)) {
                    this.Usua_DniField = value;
                    this.RaisePropertyChanged("Usua_Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usua_Nombre {
            get {
                return this.Usua_NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.Usua_NombreField, value) != true)) {
                    this.Usua_NombreField = value;
                    this.RaisePropertyChanged("Usua_Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyReserva.IServicioReservas")]
    public interface IServicioReservas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetAllReservasCliente", ReplyAction="http://tempuri.org/IServicioReservas/GetAllReservasClienteResponse")]
        MVC_Cliente.ProxyReserva.ReservaBE[] GetAllReservasCliente(short idUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetAllReservasCliente", ReplyAction="http://tempuri.org/IServicioReservas/GetAllReservasClienteResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetAllReservasClienteAsync(short idUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetAllReservasPorDia", ReplyAction="http://tempuri.org/IServicioReservas/GetAllReservasPorDiaResponse")]
        MVC_Cliente.ProxyReserva.ReservaBE[] GetAllReservasPorDia(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetAllReservasPorDia", ReplyAction="http://tempuri.org/IServicioReservas/GetAllReservasPorDiaResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetAllReservasPorDiaAsync(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetAllReservasPorDiaRestaurante", ReplyAction="http://tempuri.org/IServicioReservas/GetAllReservasPorDiaRestauranteResponse")]
        MVC_Cliente.ProxyReserva.ReservaBE[] GetAllReservasPorDiaRestaurante(System.DateTime fecha, short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetAllReservasPorDiaRestaurante", ReplyAction="http://tempuri.org/IServicioReservas/GetAllReservasPorDiaRestauranteResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetAllReservasPorDiaRestauranteAsync(System.DateTime fecha, short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/InsertReserva", ReplyAction="http://tempuri.org/IServicioReservas/InsertReservaResponse")]
        bool InsertReserva(MVC_Cliente.ProxyReserva.ReservaBE objReservaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/InsertReserva", ReplyAction="http://tempuri.org/IServicioReservas/InsertReservaResponse")]
        System.Threading.Tasks.Task<bool> InsertReservaAsync(MVC_Cliente.ProxyReserva.ReservaBE objReservaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/CancelReserva", ReplyAction="http://tempuri.org/IServicioReservas/CancelReservaResponse")]
        bool CancelReserva(short idUsua, short idReser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/CancelReserva", ReplyAction="http://tempuri.org/IServicioReservas/CancelReservaResponse")]
        System.Threading.Tasks.Task<bool> CancelReservaAsync(short idUsua, short idReser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetAllReservasRestaurante", ReplyAction="http://tempuri.org/IServicioReservas/GetAllReservasRestauranteResponse")]
        MVC_Cliente.ProxyReserva.ReservaBE[] GetAllReservasRestaurante(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetAllReservasRestaurante", ReplyAction="http://tempuri.org/IServicioReservas/GetAllReservasRestauranteResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetAllReservasRestauranteAsync(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/UpdateEstadoReserva", ReplyAction="http://tempuri.org/IServicioReservas/UpdateEstadoReservaResponse")]
        void UpdateEstadoReserva(short idUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/UpdateEstadoReserva", ReplyAction="http://tempuri.org/IServicioReservas/UpdateEstadoReservaResponse")]
        System.Threading.Tasks.Task UpdateEstadoReservaAsync(short idUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetTopUsuariosReservasRestaurante", ReplyAction="http://tempuri.org/IServicioReservas/GetTopUsuariosReservasRestauranteResponse")]
        MVC_Cliente.ProxyReserva.ReservaBE[] GetTopUsuariosReservasRestaurante(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetTopUsuariosReservasRestaurante", ReplyAction="http://tempuri.org/IServicioReservas/GetTopUsuariosReservasRestauranteResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetTopUsuariosReservasRestauranteAsync(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetCantPersonasReservas", ReplyAction="http://tempuri.org/IServicioReservas/GetCantPersonasReservasResponse")]
        short GetCantPersonasReservas(System.DateTime fecha, short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReservas/GetCantPersonasReservas", ReplyAction="http://tempuri.org/IServicioReservas/GetCantPersonasReservasResponse")]
        System.Threading.Tasks.Task<short> GetCantPersonasReservasAsync(System.DateTime fecha, short idResta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioReservasChannel : MVC_Cliente.ProxyReserva.IServicioReservas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReservasClient : System.ServiceModel.ClientBase<MVC_Cliente.ProxyReserva.IServicioReservas>, MVC_Cliente.ProxyReserva.IServicioReservas {
        
        public ServicioReservasClient() {
        }
        
        public ServicioReservasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReservasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_Cliente.ProxyReserva.ReservaBE[] GetAllReservasCliente(short idUsua) {
            return base.Channel.GetAllReservasCliente(idUsua);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetAllReservasClienteAsync(short idUsua) {
            return base.Channel.GetAllReservasClienteAsync(idUsua);
        }
        
        public MVC_Cliente.ProxyReserva.ReservaBE[] GetAllReservasPorDia(System.DateTime fecha) {
            return base.Channel.GetAllReservasPorDia(fecha);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetAllReservasPorDiaAsync(System.DateTime fecha) {
            return base.Channel.GetAllReservasPorDiaAsync(fecha);
        }
        
        public MVC_Cliente.ProxyReserva.ReservaBE[] GetAllReservasPorDiaRestaurante(System.DateTime fecha, short idResta) {
            return base.Channel.GetAllReservasPorDiaRestaurante(fecha, idResta);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetAllReservasPorDiaRestauranteAsync(System.DateTime fecha, short idResta) {
            return base.Channel.GetAllReservasPorDiaRestauranteAsync(fecha, idResta);
        }
        
        public bool InsertReserva(MVC_Cliente.ProxyReserva.ReservaBE objReservaBE) {
            return base.Channel.InsertReserva(objReservaBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertReservaAsync(MVC_Cliente.ProxyReserva.ReservaBE objReservaBE) {
            return base.Channel.InsertReservaAsync(objReservaBE);
        }
        
        public bool CancelReserva(short idUsua, short idReser) {
            return base.Channel.CancelReserva(idUsua, idReser);
        }
        
        public System.Threading.Tasks.Task<bool> CancelReservaAsync(short idUsua, short idReser) {
            return base.Channel.CancelReservaAsync(idUsua, idReser);
        }
        
        public MVC_Cliente.ProxyReserva.ReservaBE[] GetAllReservasRestaurante(short idResta) {
            return base.Channel.GetAllReservasRestaurante(idResta);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetAllReservasRestauranteAsync(short idResta) {
            return base.Channel.GetAllReservasRestauranteAsync(idResta);
        }
        
        public void UpdateEstadoReserva(short idUsua) {
            base.Channel.UpdateEstadoReserva(idUsua);
        }
        
        public System.Threading.Tasks.Task UpdateEstadoReservaAsync(short idUsua) {
            return base.Channel.UpdateEstadoReservaAsync(idUsua);
        }
        
        public MVC_Cliente.ProxyReserva.ReservaBE[] GetTopUsuariosReservasRestaurante(short idResta) {
            return base.Channel.GetTopUsuariosReservasRestaurante(idResta);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyReserva.ReservaBE[]> GetTopUsuariosReservasRestauranteAsync(short idResta) {
            return base.Channel.GetTopUsuariosReservasRestauranteAsync(idResta);
        }
        
        public short GetCantPersonasReservas(System.DateTime fecha, short idResta) {
            return base.Channel.GetCantPersonasReservas(fecha, idResta);
        }
        
        public System.Threading.Tasks.Task<short> GetCantPersonasReservasAsync(System.DateTime fecha, short idResta) {
            return base.Channel.GetCantPersonasReservasAsync(fecha, idResta);
        }
    }
}
