//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Cliente.ProxyResena {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReseñaBE", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    [System.SerializableAttribute()]
    public partial class ReseñaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Contenido_ReseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_RegistroReseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_ReseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_RestauranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Titulo_ReseñaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenido_Reseña {
            get {
                return this.Contenido_ReseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.Contenido_ReseñaField, value) != true)) {
                    this.Contenido_ReseñaField = value;
                    this.RaisePropertyChanged("Contenido_Reseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_RegistroReseña {
            get {
                return this.Fecha_RegistroReseñaField;
            }
            set {
                if ((this.Fecha_RegistroReseñaField.Equals(value) != true)) {
                    this.Fecha_RegistroReseñaField = value;
                    this.RaisePropertyChanged("Fecha_RegistroReseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Reseña {
            get {
                return this.Id_ReseñaField;
            }
            set {
                if ((this.Id_ReseñaField.Equals(value) != true)) {
                    this.Id_ReseñaField = value;
                    this.RaisePropertyChanged("Id_Reseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Restaurante {
            get {
                return this.Id_RestauranteField;
            }
            set {
                if ((this.Id_RestauranteField.Equals(value) != true)) {
                    this.Id_RestauranteField = value;
                    this.RaisePropertyChanged("Id_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Usuario {
            get {
                return this.Id_UsuarioField;
            }
            set {
                if ((this.Id_UsuarioField.Equals(value) != true)) {
                    this.Id_UsuarioField = value;
                    this.RaisePropertyChanged("Id_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Restaurante {
            get {
                return this.Nom_RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_RestauranteField, value) != true)) {
                    this.Nom_RestauranteField = value;
                    this.RaisePropertyChanged("Nom_Restaurante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo_Reseña {
            get {
                return this.Titulo_ReseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.Titulo_ReseñaField, value) != true)) {
                    this.Titulo_ReseñaField = value;
                    this.RaisePropertyChanged("Titulo_Reseña");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyResena.IServicioResenas")]
    public interface IServicioResenas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñas", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasResponse")]
        MVC_Cliente.ProxyResena.ReseñaBE[] GetAllReseñas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñas", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyResena.ReseñaBE[]> GetAllReseñasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñasRestaurante", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasRestauranteResponse")]
        MVC_Cliente.ProxyResena.ReseñaBE[] GetAllReseñasRestaurante(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñasRestaurante", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasRestauranteResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyResena.ReseñaBE[]> GetAllReseñasRestauranteAsync(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñasUsuario", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasUsuarioResponse")]
        MVC_Cliente.ProxyResena.ReseñaBE[] GetAllReseñasUsuario(short idUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetAllReseñasUsuario", ReplyAction="http://tempuri.org/IServicioResenas/GetAllReseñasUsuarioResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyResena.ReseñaBE[]> GetAllReseñasUsuarioAsync(short idUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetReseña", ReplyAction="http://tempuri.org/IServicioResenas/GetReseñaResponse")]
        MVC_Cliente.ProxyResena.ReseñaBE GetReseña(short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/GetReseña", ReplyAction="http://tempuri.org/IServicioResenas/GetReseñaResponse")]
        System.Threading.Tasks.Task<MVC_Cliente.ProxyResena.ReseñaBE> GetReseñaAsync(short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/UpdateReseña", ReplyAction="http://tempuri.org/IServicioResenas/UpdateReseñaResponse")]
        bool UpdateReseña(MVC_Cliente.ProxyResena.ReseñaBE objReseñaBE, short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/UpdateReseña", ReplyAction="http://tempuri.org/IServicioResenas/UpdateReseñaResponse")]
        System.Threading.Tasks.Task<bool> UpdateReseñaAsync(MVC_Cliente.ProxyResena.ReseñaBE objReseñaBE, short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/InsertReseña", ReplyAction="http://tempuri.org/IServicioResenas/InsertReseñaResponse")]
        bool InsertReseña(MVC_Cliente.ProxyResena.ReseñaBE objReseñaBE, short idUsua, short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/InsertReseña", ReplyAction="http://tempuri.org/IServicioResenas/InsertReseñaResponse")]
        System.Threading.Tasks.Task<bool> InsertReseñaAsync(MVC_Cliente.ProxyResena.ReseñaBE objReseñaBE, short idUsua, short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/DeleteReseña", ReplyAction="http://tempuri.org/IServicioResenas/DeleteReseñaResponse")]
        bool DeleteReseña(short idRese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResenas/DeleteReseña", ReplyAction="http://tempuri.org/IServicioResenas/DeleteReseñaResponse")]
        System.Threading.Tasks.Task<bool> DeleteReseñaAsync(short idRese);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioResenasChannel : MVC_Cliente.ProxyResena.IServicioResenas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioResenasClient : System.ServiceModel.ClientBase<MVC_Cliente.ProxyResena.IServicioResenas>, MVC_Cliente.ProxyResena.IServicioResenas {
        
        public ServicioResenasClient() {
        }
        
        public ServicioResenasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioResenasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResenasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResenasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_Cliente.ProxyResena.ReseñaBE[] GetAllReseñas() {
            return base.Channel.GetAllReseñas();
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyResena.ReseñaBE[]> GetAllReseñasAsync() {
            return base.Channel.GetAllReseñasAsync();
        }
        
        public MVC_Cliente.ProxyResena.ReseñaBE[] GetAllReseñasRestaurante(short idResta) {
            return base.Channel.GetAllReseñasRestaurante(idResta);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyResena.ReseñaBE[]> GetAllReseñasRestauranteAsync(short idResta) {
            return base.Channel.GetAllReseñasRestauranteAsync(idResta);
        }
        
        public MVC_Cliente.ProxyResena.ReseñaBE[] GetAllReseñasUsuario(short idUsua) {
            return base.Channel.GetAllReseñasUsuario(idUsua);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyResena.ReseñaBE[]> GetAllReseñasUsuarioAsync(short idUsua) {
            return base.Channel.GetAllReseñasUsuarioAsync(idUsua);
        }
        
        public MVC_Cliente.ProxyResena.ReseñaBE GetReseña(short idRese) {
            return base.Channel.GetReseña(idRese);
        }
        
        public System.Threading.Tasks.Task<MVC_Cliente.ProxyResena.ReseñaBE> GetReseñaAsync(short idRese) {
            return base.Channel.GetReseñaAsync(idRese);
        }
        
        public bool UpdateReseña(MVC_Cliente.ProxyResena.ReseñaBE objReseñaBE, short idRese) {
            return base.Channel.UpdateReseña(objReseñaBE, idRese);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateReseñaAsync(MVC_Cliente.ProxyResena.ReseñaBE objReseñaBE, short idRese) {
            return base.Channel.UpdateReseñaAsync(objReseñaBE, idRese);
        }
        
        public bool InsertReseña(MVC_Cliente.ProxyResena.ReseñaBE objReseñaBE, short idUsua, short idResta) {
            return base.Channel.InsertReseña(objReseñaBE, idUsua, idResta);
        }
        
        public System.Threading.Tasks.Task<bool> InsertReseñaAsync(MVC_Cliente.ProxyResena.ReseñaBE objReseñaBE, short idUsua, short idResta) {
            return base.Channel.InsertReseñaAsync(objReseñaBE, idUsua, idResta);
        }
        
        public bool DeleteReseña(short idRese) {
            return base.Channel.DeleteReseña(idRese);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteReseñaAsync(short idRese) {
            return base.Channel.DeleteReseñaAsync(idRese);
        }
    }
}
