//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Cliente.ProxyRestaurantes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyRestaurantes.IServicioRestaurantes")]
    public interface IServicioRestaurantes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantes", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesResponse")]
        ServiciosWCF.RestauranteBE[] GetAllRestaurantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantes", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivo", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivoResponse")]
        ServiciosWCF.RestauranteBE[] GetAllRestaurantesActivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivo", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetAllRestaurantesActivoResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesActivoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetRestauranteResponse")]
        ServiciosWCF.RestauranteBE GetRestaurante(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/GetRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/GetRestauranteResponse")]
        System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE> GetRestauranteAsync(short idResta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/InsertRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/InsertRestauranteResponse")]
        bool InsertRestaurante(ServiciosWCF.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/InsertRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/InsertRestauranteResponse")]
        System.Threading.Tasks.Task<bool> InsertRestauranteAsync(ServiciosWCF.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/UpdateRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/UpdateRestauranteResponse")]
        bool UpdateRestaurante(ServiciosWCF.RestauranteBE objRestauranteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRestaurantes/UpdateRestaurante", ReplyAction="http://tempuri.org/IServicioRestaurantes/UpdateRestauranteResponse")]
        System.Threading.Tasks.Task<bool> UpdateRestauranteAsync(ServiciosWCF.RestauranteBE objRestauranteBE);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRestaurantesChannel : Web_Cliente.ProxyRestaurantes.IServicioRestaurantes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRestaurantesClient : System.ServiceModel.ClientBase<Web_Cliente.ProxyRestaurantes.IServicioRestaurantes>, Web_Cliente.ProxyRestaurantes.IServicioRestaurantes {
        
        public ServicioRestaurantesClient() {
        }
        
        public ServicioRestaurantesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRestaurantesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRestaurantesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRestaurantesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiciosWCF.RestauranteBE[] GetAllRestaurantes() {
            return base.Channel.GetAllRestaurantes();
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesAsync() {
            return base.Channel.GetAllRestaurantesAsync();
        }
        
        public ServiciosWCF.RestauranteBE[] GetAllRestaurantesActivo() {
            return base.Channel.GetAllRestaurantesActivo();
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE[]> GetAllRestaurantesActivoAsync() {
            return base.Channel.GetAllRestaurantesActivoAsync();
        }
        
        public ServiciosWCF.RestauranteBE GetRestaurante(short idResta) {
            return base.Channel.GetRestaurante(idResta);
        }
        
        public System.Threading.Tasks.Task<ServiciosWCF.RestauranteBE> GetRestauranteAsync(short idResta) {
            return base.Channel.GetRestauranteAsync(idResta);
        }
        
        public bool InsertRestaurante(ServiciosWCF.RestauranteBE objRestauranteBE) {
            return base.Channel.InsertRestaurante(objRestauranteBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertRestauranteAsync(ServiciosWCF.RestauranteBE objRestauranteBE) {
            return base.Channel.InsertRestauranteAsync(objRestauranteBE);
        }
        
        public bool UpdateRestaurante(ServiciosWCF.RestauranteBE objRestauranteBE) {
            return base.Channel.UpdateRestaurante(objRestauranteBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRestauranteAsync(ServiciosWCF.RestauranteBE objRestauranteBE) {
            return base.Channel.UpdateRestauranteAsync(objRestauranteBE);
        }
    }
}
